### ISSUE TITLE
Please allow compile in ts strict

### ISSUE THREAD

**Issue by Rjrunner44** [energywebfoundation/iam-client-lib#104]
thx.

**Comment by jrhender** [comment]
@Rjrunner44 Do you mean that iam-client-lib should itself compile when using strict flag? This is already being done: https://github.com/energywebfoundation/iam-client-lib/blob/49120161448480f94b828309c5fac4b2fac8d21e/tsconfig.json#L28
Or do you mean that in another project when depending on iam-client-lib, you are unable to compile with typescript strict flag?

**Comment by Rjrunner44** [comment]
thx. i’m not exactly sure why ts is looking through this lib to dependencies to create the errors, as they are actually coming from passport-did-auth pulled in. i opened the issue there probably more correct.

**Comment by jrhender** [comment]
Compilation only occur when `skipLibCheck: false` and errors are in ew-did-registry packages. Issue opened in that repository to fix: https://github.com/energywebfoundation/ew-did-registry/issues/270
