### ISSUE TITLE
Feature Request: Allow Passing in identityToken expiration time

### ISSUE THREAD

**Issue by Rjrunner44** [energywebfoundation/iam-client-lib#157]
I'd like to request that the IAM client lib support allowing the user to optionally pass in the expiration time (# of blocks etc) for the identityToken returned from createIdentityProof. Thanks.

**Comment by jrhender** [comment]
The `identityToken` contains the blockNumber at the time it was generated, not the number of accepted blocks. This is configured by the verifier of the `identityToken`. @Rjrunner44 is the crux of what you want just that the server treats a given `identityToken` differently (e.g. considers a larger number of blocks or don't check the block number at all)?

**Comment by Rjrunner44** [comment]
I think it needs to check the block number. The issue is that an identityToken generated by the IAM client now can't be used for more than about 15 secs (even on the IAM swagger UI page for example)...so sometimes by the time it's created, it's already being declined by the cacheserver...if I understand it correctly.

**Comment by jrhender** [comment]
@Rjrunner44 To confirm, the feature of `passport-did-auth`, whereby the number the blocks to consider as valid can be configured, doesn't meet your requirements? https://github.com/energywebfoundation/passport-did-auth/blob/be6370b1a642d53f88a44493d4d2e89c3f66f815/lib/LoginStrategy.ts#L33
If this is the case, could you please elaborate why this is?

**Comment by Rjrunner44** [comment]
you are correct it’s not a client lib issue, i think i’m referring to doing dev against the switchboard hosted dev servers, i can’t change expiry and it’s set way too tight to be useful when doing manual steps (eg debugging code in postman etc). make sense?

R. John Anderson
702-531-4281

**Comment by jrhender** [comment]
Even if you are working with the Switchboard hosted dev servers, `passport-did-auth` remains under your full control as it is used by your backend. Therefore, I believe use of the Switchboard hosted dev servers should not prevent you from using the `numberOfBlocksBack` parameter of the `LoginStrategy` constructor. Does this make sense?

**Comment by jrhender** [comment]
Closing as `passport-did-auth` provides the `numberOfBlocksBack` parameter which allows configuration of `identityToken` expiration time
