### ISSUE TITLE
Initialization stucks forever

### ISSUE THREAD

**Issue by kosecki123** [energywebfoundation/iam-client-lib#193]
For some reason calling `const res = await iam.initializeConnection();` stucks forever without any feedback or error. 

Perhaps some parameters have not been provided?

package.json
```
{
  "name": "did-repro",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "ethers": "4.0.45",
    "iam-client-lib": "2.2.0"
  }
}
```

index.mjs
```
import { IAM } from "iam-client-lib";
import { Wallet } from "ethers";

const wallet = Wallet.createRandom();

const iam = new IAM({
  privateKey: wallet.privateKey,
  rpcUrl: "https://volta-rpc.energyweb.org/",
});

try {
  const res = await iam.initializeConnection();
} catch (e) {
  console.log(e);
}

console.log("done");

```

**Comment by kosecki123** [comment]
When running this as a test against latest develop branch

```
test("initializeConnection returns for random privateKey", async () => {
    const wallet = Wallet.createRandom();
    const iam = new IAM({ rpcUrl, privateKey: wallet.privateKey });

    const data = await iam.initializeConnection();

    expect(data).toBeDefined();
  });
```

It turns out that the privateKey has to be funded which means that `initializeConnection` does a tx in the background. Not sure what's the reason behind that tx, but we should definitely change the flow, so it is more explanatory on why we need to spend user's money just to `initialize`.

**Comment by JGiter** [comment]
The name `initializeConnection` is misleading. Except of connection this method initializes all fields of instance and also sets up user DID document. I suggest mentioning in docs that DID document is prerequisite for using iam and during initialization user proposed to create document if one doesn't exsit

**Comment by kosecki123** [comment]
Agree with @JGiter that documentation needs an update so this is clear for the users. Next step, the process should be redesigned in such a way that

1) `initConnection` function should accept an extra parameter like 'createDocumentWhenNotExist' with default value = false
2) expose `createDocument` function that does create the initial document on demand

**Comment by jrhender** [comment]
> 1. `initConnection` function should accept an extra parameter like 'createDocumentWhenNotExist' with default value = false

This is being implemented here: https://github.com/energywebfoundation/iam-client-lib/pull/208
