### ISSUE TITLE
Minimized code in the NPM packages

### ISSUE THREAD

**Issue by kosecki123** [energywebfoundation/iam-client-lib#195]
Is there any particular reason to publish minimized library code to NPM? The typical use case is that the application (node/web) is the one that bundles and minimizes their dependencies if necessary.

This also makes the debugging or trying to make sense out of stack traces impossible/superhard.

**Comment by jrhender** [comment]
latest canary version is not minimized: https://www.npmjs.com/package/iam-client-lib/v/3.0.0-alpha.23
