### ISSUE TITLE
UID field should be named ID on IRole, IOrganization and IApp interfaces

### ISSUE THREAD

**Issue by TendTo** [energywebfoundation/iam-client-lib#233]
The interfaces _IRole_, _IOrganization_ and _IApp_, specified in the [src/cacheServerClient/cacheServerClient.types.ts](https://github.com/energywebfoundation/iam-client-lib/blob/develop/src/cacheServerClient/cacheServerClient.types.ts) file use an **uid** field. In the actual object, however, this field is named **id**.

## Steps to reproduce (typescript)
```typescript
const org = await iam.getOrgHierarchy({ namespace: "namespace.iam.ewc" });
```

## Expected Behavior
```typescript
console.log((org as any).id)    //undefined
console.log(org.uid)   //org uid value
```

## Actual Behavior
```typescript
console.log((org as any).id)    //org id value
console.log(org.uid)   //undefined
```

## Specifications

  - Version: 3.0.0-alpha.38
  - Platform: windows

## Suggestion
Rename the field from uid -> id

**Comment by Harasz** [comment]
Hi @TendTo, 
someone from our team will be working on fixing that. Thanks for reporting.

**Comment by Harasz** [comment]
Fixed in https://www.npmjs.com/package/iam-client-lib/v/4.1.0-alpha.6
