### ISSUE TITLE
EW Switchboard Dapp Application Local Deployment UI Issue | Blank Application

### ISSUE THREAD

**Issue by Nick-Goorwah** [energywebfoundation/iam-client-lib#462]
Please see attached Switchboard dapp deployment issues with home page on deployment:

<img width="1277" alt="2022-01-24_13-22-57-Blank-HomePage-SwitchboardDapp" src="https://user-images.githubusercontent.com/96750818/153972812-cbf057d7-c031-4eb8-8c66-bf13c563eff7.png">
[SwitchBoard-dapp-UI-Issue.txt](https://github.com/energywebfoundation/iam-client-lib/files/8064952/SwitchBoard-dapp-UI-Issue.txt)

**Comment by Harasz** [comment]
Hi, any errors in browser console?

**Comment by Nick-Goorwah** [comment]
nick@MSI MINGW64 ~/Desktop/VolterraTechnology/switchboard-dapp (develop)
$ npm run build

> switchboard-iam@1.2.0-alpha build C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp
> node --max_old_space_size=8048 node_modules/@angular/cli/bin/ng build --prod --aot -c=develop

b Browser application bundle generation complete.
b ES5 bundle generation complete.
b Copying assets complete.
b Index html generation complete.
b Service worker generation complete.

Initial Chunk Files                      | Names                |      Size
main-es5.89ed229f181f6f36f251.js         | main                 |   6.03 MB
main-es2015.89ed229f181f6f36f251.js      | main                 |   5.50 MB
scripts.d7783a46b8fc4ec82b7e.js          | scripts              | 594.61 kB
styles.ba8aa7699c220166bbb0.css          | styles               | 488.71 kB
polyfills-es5.889bdb52b73c7412c267.js    | polyfills-es5        | 151.60 kB
polyfills-es2015.650e71bec53ff057316f.js | polyfills            |  55.87 kB
runtime-es2015.527272443e9e8850c47f.js   | runtime              |   2.43 kB
runtime-es5.527272443e9e8850c47f.js      | runtime              |   2.43 kB

                                         | Initial ES5 Total    |   7.24 MB
                                         | Initial ES2015 Total |   6.62 MB

Lazy Chunk Files                         | Names                |      Size
2-es5.6c1015b5622f271d9095.js            | -                    | 428.61 kB
2-es2015.6c1015b5622f271d9095.js         | -                    | 416.19 kB
12-es5.2927fde606d8869adfd1.js           | -                    | 390.06 kB
12-es2015.2927fde606d8869adfd1.js        | -                    | 369.48 kB
16-es5.2b2e6444740c57b024d0.js           | -                    | 110.88 kB
16-es2015.2b2e6444740c57b024d0.js        | -                    |  93.31 kB
11-es5.80b36315cdb720518aa0.js           | -                    |  83.64 kB
11-es2015.80b36315cdb720518aa0.js        | -                    |  78.64 kB
default.css                              | default              |  29.19 kB
stedin.css                               | stedin               |  28.97 kB
14-es5.08bf87f1f370bd12923e.js           | -                    |  28.68 kB
14-es2015.08bf87f1f370bd12923e.js        | -                    |  23.86 kB
1-es5.2f5e31bdcfd6e27b808e.js            | -                    |  20.79 kB
3-es5.1f41b3cb6a9cf14bae5e.js            | -                    |  20.79 kB
1-es2015.2f5e31bdcfd6e27b808e.js         | -                    |  18.37 kB
3-es2015.1f41b3cb6a9cf14bae5e.js         | -                    |  14.34 kB
theme-a.css                              | theme-a              |  14.31 kB
15-es5.3d51cc49628c56c6045c.js           | -                    |  11.39 kB
15-es2015.3d51cc49628c56c6045c.js        | -                    |  10.62 kB
13-es5.d286cc61de70a8248825.js           | -                    |   8.43 kB
13-es2015.d286cc61de70a8248825.js        | -                    |   7.80 kB

Build at: 2022-01-24T18:14:54.192Z - Hash: 365e107d8e892ef7e3e9 - Time: 124945ms

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\ng-qrcode\__ivy_ngcc__\fesm2015\ng-qrcode.js depends on 'qrcode'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\@walletconnect\iso-crypto\dist\esm\index.js depends on '@walletconnect/encoding'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\@walletconnect\browser-utils\dist\esm\browser.js depends on '@walletconnect/window-metadata'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\iam-client-lib\node_modules\@ethersproject\bignumber\lib.esm\bignumber.js depends on 'bn.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\@walletconnect\jsonrpc-utils\dist\esm\env.js depends on '@walletconnect/environment'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\iam-client-lib\node_modules\@ethersproject\signing-key\lib.esm\elliptic.js depends on 'hash.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\@walletconnect\core\dist\esm\index.js depends on '@walletconnect/socket-transport'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\@walletconnect\utils\dist\esm\encoding.js depends on 'bn.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\@walletconnect\utils\dist\esm\url.js depends on 'query-string'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies



nick@MSI MINGW64 ~/Desktop/VolterraTechnology/switchboard-dapp (develop)
$ npm run start

> switchboard-iam@1.2.0-alpha start C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp
> ng serve

b Browser application bundle generation complete.

Initial Chunk Files                                                                                 | Names                                                                                            |      Size
vendor.js                                                                                           | vendor                                                                                           |  15.66 MB
scripts.js                                                                                          | scripts                                                                                          |   1.14 MB
main.js                                                                                             | main                                                                                             |   1.01 MB
styles.css, styles.js                                                                               | styles                                                                                           | 948.25 kB
polyfills.js                                                                                        | polyfills                                                                                        | 564.24 kB
default.css, default.js                                                                             | default                                                                                          | 387.92 kB
stedin.css, stedin.js                                                                               | stedin                                                                                           | 387.79 kB
theme-a.css, theme-a.js                                                                             | theme-a                                                                                          | 368.64 kB
runtime.js                                                                                          | runtime                                                                                          |   9.75 kB

                                                                                                    | Initial Total                                                                                    |  20.41 MB

Lazy Chunk Files                                                                                    | Names                                                                                            |      Size
default~assets-assets-module~enrolment-enrolment-module.js                                          | default~assets-assets-module~enrolment-enrolment-module                                          |   1.57 MB
applications-applications-module.js                                                                 | applications-applications-module                                                                 |   1.18 MB
search-result-search-result-module.js                                                               | search-result-search-result-module                                                               | 455.86 kB
assets-assets-module.js                                                                             | assets-assets-module                                                                             | 340.36 kB
dashboard-dashboard-module.js                                                                       | dashboard-dashboard-module                                                                       | 281.11 kB
default~applications-applications-module~assets-assets-module~search-result-search-result-module.js | default~applications-applications-module~assets-assets-module~search-result-search-result-module |  74.57 kB
enrolment-enrolment-module.js                                                                       | enrolment-enrolment-module                                                                       |  63.92 kB
default~applications-applications-module~assets-assets-module.js                                    | default~applications-applications-module~assets-assets-module                                    |  38.10 kB
welcome-welcome-module.js                                                                           | welcome-welcome-module                                                                           |  21.32 kB

Build at: 2022-01-24T18:15:44.074Z - Hash: 613aae350e952ad3fb23 - Time: 25117ms

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\src\app\app.module.ts depends on 'hammerjs'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\iam-client-lib\node_modules\@ethersproject\bignumber\lib.esm\bignumber.js depends on 'bn.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\@ethersproject\signing-key\lib.esm\elliptic.js depends on 'hash.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\@walletconnect\core\dist\esm\index.js depends on '@walletconnect/socket-transport'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\@walletconnect\browser-utils\dist\esm\browser.js depends on '@walletconnect/window-metadata'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\@walletconnect\iso-crypto\dist\esm\index.js depends on '@walletconnect/encoding'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\@walletconnect\utils\dist\esm\encoding.js depends on 'bn.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\@walletconnect\utils\dist\esm\url.js depends on 'query-string'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\@walletconnect\crypto\dist\esm\lib\browser.js depends on '@walletconnect/environment'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Users\nick\Desktop\VolterraTechnology\switchboard-dapp\node_modules\ng-qrcode\__ivy_ngcc__\fesm2015\ng-qrcode.js depends on 'qrcode'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies



** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


b Compiled successfully.

**Comment by Harasz** [comment]
I close due to inactivity
