### ISSUE TITLE
React Demo Taking Gas but not loading 

### ISSUE THREAD

**Issue by S-Burns** [energywebfoundation/iam-client-lib#79]
Metamask ETH was withdrawn multiple times from the react demo link but failed to load or time out

**Comment by jrhender** [comment]
Thanks @S-Burns for reporting. I believe that your issue may have occurred while the claims cache server was inaccessible. I tried to reproduce your error during this time and noticed that the timeout before an error on client was displayed was quite long. Are you currently able to reproduce? (link to react demo: https://did-auth-demo.energyweb.org/react-example/)

**Comment by jrhender** [comment]
Perhaps to improve the UX here we can:
- Shorten the timeout
- Failover to the blockchain if the cache is inaccessible

**Comment by jrhender** [comment]
Closing issue as:
- Story added to backlog to add chainID notifications to example (demo) iam-client apps
- Example apps have been moved here: https://github.com/energywebfoundation/iam-client-examples
